name: python-test-actions

on:
  push:
    branches: ["main"]

jobs:
  build1:
    runs-on: ubuntu-latest

    steps:
      - name: cloning source code
        use: actions/checkout@v3
      - name: setuping python version
        use: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: installing dependencies by mridul
        run: pip install requirements.txt
      - name: testing code quality and code coverage......
        run : |
          pytest
          coverage -m run pytest
          coverage report -m
